sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t mereszd/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mereszd/docker-react npm run test